<x-layouts.app :title="config('app.name').' System Status'">
    <x-app-shell page-title="System Status" section-label="Diagnostics and Resilience">
        <x-slot:actions><a href="{{ route('dashboard') }}" class="btn-secondary">Back to Dashboard</a>@if (auth()->user()?->hasPermission('settings.manage'))<a href="{{ route('backups.index') }}" class="btn-primary">Backups</a>@endif</x-slot>
        <div class="space-y-5">
            <section class="surface-panel overflow-hidden"><div class="grid gap-0 lg:grid-cols-[1.3fr_1fr]"><div class="border-b border-slate-200/80 p-6 lg:border-b-0 lg:border-r"><p class="section-kicker">Local installation</p><h2 class="mt-2 text-2xl font-semibold text-ink-950">Runtime health and resilience</h2><p class="mt-3 max-w-2xl text-sm leading-6 text-slate-600">This page checks the workstation, database connection, local paths, offline operating mode, and configured device readiness. It is separate from daily store performance.</p></div><div class="grid grid-cols-2 divide-x divide-y divide-slate-200/80"><div class="p-5"><p class="metric-label">Version</p><p class="mt-2 text-xl font-semibold text-medical-700">{{ $status['application']['version'] }}</p></div><div class="p-5"><p class="metric-label">Environment</p><p class="mt-2 text-xl font-semibold text-ink-950">{{ $status['application']['environment'] }}</p></div><div class="p-5"><p class="metric-label">Database</p><p class="mt-2 text-xl font-semibold {{ $status['database']['connected'] ? 'text-medical-700' : 'text-red-700' }}">{{ $status['database']['connected'] ? 'Connected' : 'Failed' }}</p></div><div class="p-5"><p class="metric-label">Offline Core</p><p class="mt-2 text-xl font-semibold text-medical-700">Ready</p></div></div></div></section>
            <livewire:system-status-panel />
            <livewire:hardware-status-panel />
            <section class="surface-panel p-5"><p class="section-kicker">Operational notes</p><div class="mt-4 grid gap-3 md:grid-cols-3"><div class="rounded-lg border border-slate-200 bg-slate-50 p-4"><p class="font-semibold text-ink-950">Multi-counter mode</p><p class="mt-1 text-sm text-slate-600">Intentionally disabled for this release phase.</p></div><div class="rounded-lg border border-slate-200 bg-slate-50 p-4"><p class="font-semibold text-ink-950">Online services</p><p class="mt-1 text-sm text-slate-600">Optional integrations stay outside the offline billing core.</p></div><div class="rounded-lg border border-slate-200 bg-slate-50 p-4"><p class="font-semibold text-ink-950">Backup discipline</p><p class="mt-1 text-sm text-slate-600">Create and verify a backup before upgrades or restore operations.</p></div></div></section>
        </div>
    </x-app-shell>
</x-layouts.app>
