<x-layouts.app :title="config('app.name').' Stock Adjustments'">
    <x-app-shell page-title="Stock Adjustments" section-label="Inventory Control">
        <x-slot:actions><a href="{{ route('inventory.batches.index') }}" class="btn-secondary">Inventory Batches</a><a href="{{ route('inventory.adjustments.create') }}" class="btn-primary">New Adjustment</a></x-slot>
        <div class="space-y-5">
            <section class="grid gap-3 md:grid-cols-3"><div class="metric-tile"><p class="metric-label">Finalized Documents</p><p class="mt-2 text-3xl font-semibold text-medical-700">{{ $adjustments->count() }}</p></div><div class="metric-tile"><p class="metric-label">Changed Lines</p><p class="mt-2 text-3xl font-semibold text-ink-950">{{ $adjustments->sum(fn ($adjustment) => $adjustment->items->count()) }}</p></div><div class="metric-tile"><p class="metric-label">Latest Date</p><p class="mt-2 text-3xl font-semibold text-alert-700">{{ $adjustments->first()?->adjustment_date?->format('d M Y') ?: 'None' }}</p></div></section>
            <section class="surface-panel overflow-hidden"><div class="border-b border-slate-200 bg-white p-5"><p class="section-kicker">Immutable count corrections</p><h2 class="mt-1 text-lg font-semibold text-ink-950">Adjustment history</h2></div><div class="overflow-x-auto"><table class="min-w-full divide-y divide-slate-200 text-left text-sm"><thead class="table-header"><tr><th class="px-4 py-3">Document</th><th class="px-4 py-3">Date</th><th class="px-4 py-3">Reason</th><th class="px-4 py-3">Lines</th><th class="px-4 py-3 text-right">Action</th></tr></thead><tbody class="divide-y divide-slate-100 bg-white">@forelse ($adjustments as $adjustment)<tr><td class="px-4 py-3"><a href="{{ route('inventory.adjustments.show', $adjustment) }}" class="font-semibold text-medical-700 hover:underline">{{ $adjustment->adjustment_number }}</a><p class="mt-1 text-xs text-slate-500">{{ ucfirst($adjustment->status) }}</p></td><td class="px-4 py-3 text-slate-700">{{ $adjustment->adjustment_date?->format('d M Y') }}</td><td class="px-4 py-3 text-slate-700">{{ $adjustment->reason }}</td><td class="px-4 py-3 text-slate-700">{{ $adjustment->items->count() }}</td><td class="px-4 py-3 text-right"><a href="{{ route('inventory.adjustments.show', $adjustment) }}" class="btn-secondary">View</a></td></tr>@empty<tr><td colspan="5" class="px-4 py-12 text-center text-sm font-medium text-slate-500">No stock adjustments have been finalized.</td></tr>@endforelse</tbody></table></div></section>
        </div>
    </x-app-shell>
</x-layouts.app>
