<?php

return [
    'permissions' => [
        'system.status.view' => [
            'name' => 'View system status',
            'module' => 'system',
            'description' => 'View local runtime, storage, and offline-readiness status.',
            'is_sensitive' => false,
        ],
        'setup.manage' => [
            'name' => 'Manage setup',
            'module' => 'setup',
            'description' => 'Maintain store setup and installation profile records.',
            'is_sensitive' => true,
        ],
        'settings.manage' => [
            'name' => 'Manage settings',
            'module' => 'settings',
            'description' => 'Change local application settings.',
            'is_sensitive' => true,
        ],
        'reports.view' => [
            'name' => 'View operational reports',
            'module' => 'reports',
            'description' => 'View sales, inventory, refill, cash, and controlled-medicine operational reports.',
            'is_sensitive' => true,
        ],
        'accounting.view' => [
            'name' => 'View accounting journals',
            'module' => 'accounting',
            'description' => 'Review posted journal entries, account balances, and source documents.',
            'is_sensitive' => true,
        ],
        'accounting.manage' => [
            'name' => 'Manage accounting postings',
            'module' => 'accounting',
            'description' => 'Manage accounting configuration and controlled posting workflows.',
            'is_sensitive' => true,
        ],
        'users.manage' => [
            'name' => 'Manage users',
            'module' => 'access',
            'description' => 'Create, update, and disable local user accounts.',
            'is_sensitive' => true,
        ],
        'roles.manage' => [
            'name' => 'Manage roles and permissions',
            'module' => 'access',
            'description' => 'Assign roles and permission sets.',
            'is_sensitive' => true,
        ],
        'audit.view' => [
            'name' => 'View audit log',
            'module' => 'audit',
            'description' => 'View security and operational audit events.',
            'is_sensitive' => true,
        ],
        'sensitive.approve' => [
            'name' => 'Approve sensitive actions',
            'module' => 'audit',
            'description' => 'Approve workflows that require an authorized local user.',
            'is_sensitive' => true,
        ],
        'catalogue.view' => [
            'name' => 'View catalogue',
            'module' => 'catalogue',
            'description' => 'View product and medicine catalogue records.',
            'is_sensitive' => false,
        ],
        'catalogue.manage' => [
            'name' => 'Manage catalogue',
            'module' => 'catalogue',
            'description' => 'Create and maintain product and medicine catalogue records.',
            'is_sensitive' => true,
        ],
        'tax_rates.manage' => [
            'name' => 'Manage tax rates',
            'module' => 'catalogue',
            'description' => 'Create and maintain configurable tax-rate records.',
            'is_sensitive' => true,
        ],
        'suppliers.view' => [
            'name' => 'View suppliers',
            'module' => 'suppliers',
            'description' => 'View supplier and distributor profile records.',
            'is_sensitive' => false,
        ],
        'suppliers.manage' => [
            'name' => 'Manage suppliers',
            'module' => 'suppliers',
            'description' => 'Create and maintain supplier and distributor profile records.',
            'is_sensitive' => true,
        ],
        'customers.view' => [
            'name' => 'View customers',
            'module' => 'customers',
            'description' => 'View customer profiles, balances, and billing-linked records.',
            'is_sensitive' => true,
        ],
        'customers.manage' => [
            'name' => 'Manage customers',
            'module' => 'customers',
            'description' => 'Create and maintain customer profiles, balances, and communication consents.',
            'is_sensitive' => true,
        ],
        'patients.view' => [
            'name' => 'View patients',
            'module' => 'patients',
            'description' => 'View patient identities, contact details, and clinical notes.',
            'is_sensitive' => true,
        ],
        'patients.manage' => [
            'name' => 'Manage patients',
            'module' => 'patients',
            'description' => 'Create and maintain patient records, allergies, and consent details.',
            'is_sensitive' => true,
        ],
        'doctors.view' => [
            'name' => 'View doctors',
            'module' => 'doctors',
            'description' => 'View doctor profiles, registration details, and linked clinical records.',
            'is_sensitive' => true,
        ],
        'doctors.manage' => [
            'name' => 'Manage doctors',
            'module' => 'doctors',
            'description' => 'Create and maintain doctor profiles and contact details.',
            'is_sensitive' => true,
        ],
        'prescriptions.view' => [
            'name' => 'View prescriptions',
            'module' => 'prescriptions',
            'description' => 'View prescription records, attachments, and dispensing history.',
            'is_sensitive' => true,
        ],
        'prescriptions.manage' => [
            'name' => 'Manage prescriptions',
            'module' => 'prescriptions',
            'description' => 'Create and maintain prescription records and linked dispensing details.',
            'is_sensitive' => true,
        ],
        'controlled_medicines.view' => [
            'name' => 'View controlled medicine register',
            'module' => 'controlled_medicines',
            'description' => 'View controlled-medicine dispensing and reversal register entries.',
            'is_sensitive' => true,
        ],
        'purchases.view' => [
            'name' => 'View purchases',
            'module' => 'purchases',
            'description' => 'View purchase order and purchase-management foundation records.',
            'is_sensitive' => false,
        ],
        'purchases.manage' => [
            'name' => 'Manage purchases',
            'module' => 'purchases',
            'description' => 'Create and maintain purchase order foundation records.',
            'is_sensitive' => true,
        ],
        'inventory.view' => [
            'name' => 'View inventory',
            'module' => 'inventory',
            'description' => 'View product batches, expiry, and stock movement records.',
            'is_sensitive' => false,
        ],
        'inventory.manage' => [
            'name' => 'Manage inventory',
            'module' => 'inventory',
            'description' => 'Receive stock and create audited inventory movements.',
            'is_sensitive' => true,
        ],
        'inventory.adjust' => [
            'name' => 'Adjust inventory',
            'module' => 'inventory',
            'description' => 'Finalize sensitive stock-count adjustments with an immutable movement and audit trail.',
            'is_sensitive' => true,
        ],
        'sales.view' => [
            'name' => 'View sales',
            'module' => 'sales',
            'description' => 'View POS billing and sales invoice records.',
            'is_sensitive' => false,
        ],
        'sales.manage' => [
            'name' => 'Manage sales',
            'module' => 'sales',
            'description' => 'Create and cancel POS billing records with audited stock movements.',
            'is_sensitive' => true,
        ],
        'cash_drawer.view' => [
            'name' => 'View cash drawer',
            'module' => 'cash_drawer',
            'description' => 'View cash drawer shifts, cash movements, and reconciliation totals.',
            'is_sensitive' => true,
        ],
        'cash_drawer.manage' => [
            'name' => 'Manage cash drawer',
            'module' => 'cash_drawer',
            'description' => 'Open, reconcile, close, and record audited cash drawer movements.',
            'is_sensitive' => true,
        ],
    ],

    'roles' => [
        'owner' => [
            'name' => 'Owner',
            'description' => 'Primary store owner with full access to foundation modules.',
            'is_system' => true,
            'permissions' => [
                'system.status.view',
                'setup.manage',
                'settings.manage',
                'reports.view',
                'accounting.view',
                'accounting.manage',
                'users.manage',
                'roles.manage',
                'audit.view',
                'sensitive.approve',
                'catalogue.view',
                'catalogue.manage',
                'tax_rates.manage',
                'suppliers.view',
                'suppliers.manage',
                'customers.view',
                'customers.manage',
                'patients.view',
                'patients.manage',
                'doctors.view',
                'doctors.manage',
                'prescriptions.view',
                'prescriptions.manage',
                'controlled_medicines.view',
                'purchases.view',
                'purchases.manage',
                'inventory.view',
                'inventory.manage',
                'inventory.adjust',
                'sales.view',
                'sales.manage',
                'cash_drawer.view',
                'cash_drawer.manage',
            ],
        ],
        'manager' => [
            'name' => 'Store Manager',
            'description' => 'Operational manager for catalogue, purchasing, inventory, sales, reporting, and customer workflows.',
            'is_system' => true,
            'permissions' => [
                'system.status.view',
                'reports.view',
                'accounting.view',
                'accounting.manage',
                'catalogue.view',
                'catalogue.manage',
                'tax_rates.manage',
                'suppliers.view',
                'suppliers.manage',
                'customers.view',
                'customers.manage',
                'patients.view',
                'patients.manage',
                'doctors.view',
                'doctors.manage',
                'prescriptions.view',
                'prescriptions.manage',
                'controlled_medicines.view',
                'purchases.view',
                'purchases.manage',
                'inventory.view',
                'inventory.manage',
                'inventory.adjust',
                'sales.view',
                'sales.manage',
                'cash_drawer.view',
                'cash_drawer.manage',
            ],
        ],
        'pharmacist' => [
            'name' => 'Pharmacist',
            'description' => 'Dispensing-focused access to products, inventory, patients, prescriptions, controlled medicines, and billing.',
            'is_system' => true,
            'permissions' => [
                'system.status.view',
                'reports.view',
                'catalogue.view',
                'catalogue.manage',
                'suppliers.view',
                'customers.view',
                'customers.manage',
                'patients.view',
                'patients.manage',
                'doctors.view',
                'prescriptions.view',
                'prescriptions.manage',
                'controlled_medicines.view',
                'inventory.view',
                'inventory.manage',
                'sales.view',
                'sales.manage',
                'cash_drawer.view',
            ],
        ],
        'cashier' => [
            'name' => 'Cashier',
            'description' => 'Counter access for customer lookup, barcode billing, returns, and cash drawer operations.',
            'is_system' => true,
            'permissions' => [
                'system.status.view',
                'reports.view',
                'catalogue.view',
                'customers.view',
                'customers.manage',
                'sales.view',
                'sales.manage',
                'cash_drawer.view',
                'cash_drawer.manage',
            ],
        ],
    ],
];
