<x-app-shell page-title="Backups" section-label="Resilience">
    <x-slot:actions><a href="{{ route('settings.index') }}" class="btn-secondary">Settings</a><button type="button" wire:click="createBackup" class="btn-primary">Create Database Backup</button></x-slot>
    <div class="space-y-5">
        @if (session('status'))<div class="surface-panel border-medical-100 bg-medical-50 px-4 py-3 text-sm font-semibold text-medical-800">{{ session('status') }}</div>@endif
        @error('backup')<div class="surface-panel border-red-100 bg-red-50 px-4 py-3 text-sm font-semibold text-red-800">{{ $message }}</div>@enderror
        @error('restore')<div class="surface-panel border-red-100 bg-red-50 px-4 py-3 text-sm font-semibold text-red-800">{{ $message }}</div>@enderror
        <section class="grid gap-3 md:grid-cols-3"><div class="metric-tile"><p class="metric-label">Backup Directory</p><p class="mt-2 break-all text-sm font-semibold text-ink-950">{{ $summary['path'] }}</p></div><div class="metric-tile"><p class="metric-label">Directory</p><p class="mt-2 text-2xl font-semibold {{ $summary['directory_exists'] ? 'text-medical-700' : 'text-red-700' }}">{{ $summary['directory_exists'] ? 'Ready' : 'Missing' }}</p></div><div class="metric-tile"><p class="metric-label">Writable</p><p class="mt-2 text-2xl font-semibold {{ $summary['writable'] ? 'text-medical-700' : 'text-red-700' }}">{{ $summary['writable'] ? 'Yes' : 'No' }}</p></div></section>
        <section class="surface-panel overflow-hidden"><div class="border-b border-slate-200 bg-white p-5"><p class="section-kicker">Verified database artifacts</p><h2 class="mt-1 text-lg font-semibold text-ink-950">Backup history</h2><p class="mt-2 text-sm text-slate-600">Backups are local SQLite files with a SHA-256 checksum. Restore creates a pre-restore safety copy before replacing the active database.</p></div><div class="overflow-x-auto"><table class="min-w-full divide-y divide-slate-200 text-left text-sm"><thead class="table-header"><tr><th class="px-4 py-3">File</th><th class="px-4 py-3">Status</th><th class="px-4 py-3">Created</th><th class="px-4 py-3">Checksum</th><th class="px-4 py-3 text-right">Action</th></tr></thead><tbody class="divide-y divide-slate-100 bg-white">@forelse ($jobs as $job)<tr><td class="px-4 py-3"><p class="font-semibold text-ink-950">{{ $job->file_name }}</p><p class="mt-1 text-xs text-slate-500">{{ $job->file_size ? number_format($job->file_size).' bytes' : 'No file size' }}</p></td><td class="px-4 py-3"><span class="badge {{ $job->status === 'completed' ? 'bg-medical-50 text-medical-700' : ($job->status === 'failed' ? 'bg-red-50 text-red-700' : 'bg-alert-50 text-alert-700') }}">{{ ucfirst($job->status) }}</span></td><td class="px-4 py-3 text-slate-700">{{ $job->created_at?->format('d M Y H:i') }}</td><td class="max-w-72 break-all px-4 py-3 text-xs text-slate-500">{{ $job->checksum ?: $job->message }}</td><td class="px-4 py-3 text-right">@if ($job->status === 'completed' && is_file($job->file_path))<button type="button" wire:click="restore({{ $job->id }})" wire:confirm="Restore this backup and replace the active database?" class="btn-secondary">Restore</button>@else<span class="text-xs text-slate-500">Unavailable</span>@endif</td></tr>@empty<tr><td colspan="5" class="px-4 py-12 text-center text-sm font-medium text-slate-500">No database backups have been created.</td></tr>@endforelse</tbody></table></div></section>
    </div>
</x-app-shell>
