<x-layouts.app :title="config('app.name').' Purchase Return Detail'">
    <x-app-shell :page-title="$purchaseReturn->return_number" section-label="Purchase Return Detail">
        <x-slot:actions>
            <a href="{{ route('purchase-returns.index') }}" class="btn-secondary">Back to Returns</a>
            <a href="{{ route('purchase-invoices.show', $purchaseReturn->purchaseInvoice) }}" class="btn-secondary">Source Invoice</a>
            <a href="{{ route('suppliers.ledger', $purchaseReturn->supplier) }}" class="btn-primary">Supplier Ledger</a>
        </x-slot>

        <div class="space-y-5">
            <section class="surface-panel p-5"><div class="flex flex-col gap-3 border-b border-slate-200 pb-4 sm:flex-row sm:items-start sm:justify-between"><div><p class="section-kicker">Immutable supplier return</p><h1 class="mt-1 text-2xl font-semibold text-ink-950">{{ $purchaseReturn->return_number }}</h1><p class="mt-2 text-sm text-slate-600">{{ $purchaseReturn->supplier?->name }} / {{ $purchaseReturn->purchaseInvoice?->invoice_number }}</p></div><span class="badge bg-medical-50 text-medical-700">{{ ucfirst($purchaseReturn->status) }}</span></div><dl class="mt-5 grid gap-4 md:grid-cols-4"><div class="rounded-lg border border-slate-200 bg-slate-50/70 p-4"><dt class="field-label">Return Date</dt><dd class="mt-2 font-semibold text-ink-950">{{ $purchaseReturn->return_date?->format('d M Y') }}</dd></div><div class="rounded-lg border border-slate-200 bg-slate-50/70 p-4"><dt class="field-label">Reason</dt><dd class="mt-2 font-semibold text-ink-950">{{ $purchaseReturn->reason ?: 'Not specified' }}</dd></div><div class="rounded-lg border border-slate-200 bg-slate-50/70 p-4"><dt class="field-label">Supplier Credit</dt><dd class="mt-2 font-semibold text-alert-700">{{ $purchaseReturn->total_amount }}</dd></div><div class="rounded-lg border border-slate-200 bg-slate-50/70 p-4"><dt class="field-label">Finalized</dt><dd class="mt-2 font-semibold text-ink-950">{{ $purchaseReturn->finalized_at?->format('d M Y H:i') }}</dd></div></dl></section>
            <section class="surface-panel overflow-hidden"><div class="border-b border-slate-200 bg-white p-5"><p class="section-kicker">Returned Stock</p><h2 class="mt-1 text-lg font-semibold text-ink-950">Return lines</h2></div><div class="overflow-x-auto"><table class="min-w-full divide-y divide-slate-200 text-left text-sm"><thead class="table-header"><tr><th class="px-4 py-3">Product</th><th class="px-4 py-3">Batch</th><th class="px-4 py-3">Quantity</th><th class="px-4 py-3">Free</th><th class="px-4 py-3 text-right">Line Credit</th></tr></thead><tbody class="divide-y divide-slate-100 bg-white">@foreach ($purchaseReturn->items as $item)<tr><td class="px-4 py-3 font-semibold text-ink-950">{{ $item->product_name_snapshot }}</td><td class="px-4 py-3 text-slate-700">{{ $item->batch_number }}</td><td class="px-4 py-3 text-slate-700">{{ $item->quantity }}</td><td class="px-4 py-3 text-slate-700">{{ $item->free_quantity }}</td><td class="px-4 py-3 text-right font-semibold text-ink-900">{{ $item->line_total }}</td></tr>@endforeach</tbody></table></div></section>
            <section class="surface-panel p-5"><p class="section-kicker">Linked Accounting</p><h2 class="mt-1 text-lg font-semibold text-ink-950">Supplier payable reversal</h2><p class="mt-2 text-sm text-slate-600">The return creates a supplier debit and reverses inventory/input tax through a balanced journal.</p>@if ($purchaseReturn->journalEntry)<a href="{{ route('accounting.journal.show', $purchaseReturn->journalEntry) }}" class="btn-secondary mt-4">{{ $purchaseReturn->journalEntry->entry_number }}</a>@else<p class="mt-4 text-sm text-slate-500">No financial journal was required for this zero-value stock return.</p>@endif@if ($purchaseReturn->notes)<p class="mt-5 border-t border-slate-200 pt-4 text-sm text-slate-700">{{ $purchaseReturn->notes }}</p>@endif</section>
        </div>
    </x-app-shell>
</x-layouts.app>
